// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://sihcnrezhcomxcrvsrgz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNpaGNucmV6aGNvbXhjcnZzcmd6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAzNTg4NjYsImV4cCI6MjA2NTkzNDg2Nn0.IFDncHfHmtch40Mr0CMR2yEqArlEtsvWYJAO5xuFLZM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);